# Generated by Django 5.0.14 on 2026-06-13 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('nutrition_facts', models.JSONField(blank=True, null=True)),
                ('ingredients_text', models.TextField(blank=True, null=True)),
                ('health_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('HEALTHY', 'Healthy'), ('MODERATE', 'Moderate'), ('UNHEALTHY', 'Unhealthy')], default='MODERATE', max_length=15)),
                ('harmful_ingredients', models.JSONField(blank=True, default=list)),
                ('risk_explanation', models.TextField(blank=True, null=True)),
                ('consumption_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('applied_goal', models.CharField(blank=True, max_length=50, null=True)),
                ('applied_language', models.CharField(blank=True, max_length=10, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_goal', models.CharField(choices=[('GENERAL', 'General Health'), ('WEIGHT_LOSS', 'Weight Loss'), ('MUSCLE_GAIN', 'Muscle Gain'), ('DIABETES', 'Diabetes-Friendly')], default='GENERAL', max_length=20)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('health_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=15, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'barcode')},
            },
        ),
    ]
