# Generated by Django 5.0.14 on 2026-06-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthscan', '0002_userprofile_onboarding_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscanhistory',
            name='alternatives',
        ),
        migrations.RemoveField(
            model_name='productscanhistory',
            name='applied_language',
        ),
        migrations.RemoveField(
            model_name='productscanhistory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productscanhistory',
            name='consumption_frequency',
        ),
        migrations.RemoveField(
            model_name='productscanhistory',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productscanhistory',
            name='ingredients_text',
        ),
        migrations.RemoveField(
            model_name='productscanhistory',
            name='nutrition_facts',
        ),
        migrations.RemoveField(
            model_name='productscanhistory',
            name='risk_explanation',
        ),
    ]
